# Filtering and cleaning NYPD Complaint and Arrests data

* The two files:
    1. `NYPD_Complaint_Data_Historic.csv` - **https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i**
    2. `NYPD_Arrests_Data__Historic_.csv` - **https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u**


* Contain all complaints/arrests recorded from 2006 through the end of the previous calender year (2019). These two datasets are too large to work with easily. So we want to apply a file filter to select the lines that relate to sexual assaults or sex crimes, as well as remove columns not necessary for analysis.

### 1. Filtering the complaint data

1. Define a list of crime categories.
2. Read each line in the CSV file and look at the 9th field/column.
3. If it contains a string that is in the categories of interest, add current line to filter list.

In [1]:
SA_cats = ['RAPE', 'SEX CRIMES', 'FORCIBLE TOUCHING']

In [2]:
filtered_lines = []
for lnum, line in enumerate(open('../data/raw/NYPD_Complaint_Data_Historic.csv')):
    
    # add the first line of file into flitered_list (this is the column headers)
    if lnum==0:
        filtered_lines.append(line)
    
    # if the 9th field in the current line matches one of the string in SA_cats add to list
    fields = line.split(',')
    if fields[8] in SA_cats:
        filtered_lines.append(line)

* Now write out the filtered list as a CSV file

In [3]:
with open('../data/raw/NYPD_Complaint_Data_Historic_FILTERED_SAcrimes.csv', 'w') as out:
    for line in filtered_lines:
        out.write(line)

### 2. Cleaning the complaint data
1. Look at the columns in data set
2. Filter for columns necessary for analysis 
3. Create a new data frame with just those columns
2. Rename columns

In [4]:
import pandas as pd 
nyc_complaints_df = pd.read_csv('../data/raw/NYPD_Complaint_Data_Historic_FILTERED_SAcrimes.csv')

/usr/local/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (18,20) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
nyc_complaints_df.columns

Index(['CMPLNT_NUM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT',
       'CMPLNT_TO_TM', 'ADDR_PCT_CD', 'RPT_DT', 'KY_CD', 'OFNS_DESC', 'PD_CD',
       'PD_DESC', 'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'BORO_NM',
       'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'JURIS_DESC', 'JURISDICTION_CODE',
       'PARKS_NM', 'HADEVELOPT', 'HOUSING_PSA', 'X_COORD_CD', 'Y_COORD_CD',
       'SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX', 'TRANSIT_DISTRICT',
       'Latitude', 'Longitude', 'Lat_Lon', 'PATROL_BORO', 'STATION_NAME',
       'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX'],
      dtype='object')

In [6]:
cols= ['BORO_NM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT',
       'CMPLNT_TO_TM','ADDR_PCT_CD', 'RPT_DT', 'KY_CD', 'OFNS_DESC',
       'PD_DESC', 'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD',
       'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC',
       'SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX','VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX']
nyc_SA_complaints = nyc_complaints_df[cols]
cname_dict= {
    'BORO_NM': 'borough', 
    'CMPLNT_FR_DT': 'start_date', 
    'CMPLNT_FR_TM': 'start_time', 
    'CMPLNT_TO_DT': 'end_date',
    'CMPLNT_TO_TM': 'end_time',
    'ADDR_PCT_CD': 'precinct',
    'RPT_DT': 'report_date',
    'KY_CD': 'classif_code',
    'OFNS_DESC': 'offense_desc',
    'PD_DESC': 'pd_desc',
    'CRM_ATPT_CPTD_CD': 'crime_cmpltn',
    'LAW_CAT_CD': 'offense_lvl',
    'LOC_OF_OCCUR_DESC': 'location', 
    'PREM_TYP_DESC': 'premises_desc',
    'SUSP_AGE_GROUP': 'suspect_age',
    'SUSP_RACE': 'suspect_race',
    'SUSP_SEX': 'suspect_sex', 
    'VIC_AGE_GROUP': 'vic_age',
    'VIC_RACE': 'vic_race',
    'VIC_SEX': 'vic_sex'
}
nyc_SA_complaints= nyc_SA_complaints.rename(columns=cname_dict)
nyc_SA_complaints

,borough,start_date,start_time,end_date,end_time,precinct,report_date,classif_code,offense_desc,pd_desc,crime_cmpltn,offense_lvl,location,premises_desc,suspect_age,suspect_race,suspect_sex,vic_age,vic_race,vic_sex
0,BROOKLYN,10/16/2007,02:00:00,12/31/2007,03:00:00,83.0,03/11/2016,116,SEX CRIMES,SEXUAL ABUSE,COMPLETED,FELONY,INSIDE,RESIDENCE - APT. HOUSE,25-44,WHITE HISPANIC,M,<18,WHITE HISPANIC,F
1,BROOKLYN,01/01/2006,00:01:00,01/01/2006,23:59:00,75.0,10/21/2012,116,SEX CRIMES,AGGRAVATED SEXUAL ASBUSE,COMPLETED,FELONY,INSIDE,RESIDENCE-HOUSE,NaN,BLACK,M,<18,BLACK,F
2,QUEENS,02/18/2013,05:00:00,02/18/2013,05:25:00,110.0,02/18/2013,233,SEX CRIMES,"SEXUAL ABUSE 3,2",COMPLETED,MISDEMEANOR,INSIDE,RESTAURANT/DINER,NaN,NaN,NaN,18-24,WHITE HISPANIC,M
3,BROOKLYN,04/26/2015,12:00:00,04/26/2015,12:30:00,69.0,04/27/2015,116,SEX CRIMES,SEXUAL ABUSE,COMPLETED,FELONY,INSIDE,GROCERY/BODEGA,NaN,NaN,NaN,<18,BLACK,F
4,BROOKLYN,10/17/2012,01:00:00,10/17/2012,06:36:00,67.0,10/17/2012,104,RAPE,RAPE 1,COMPLETED,FELONY,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,25-44,BLACK,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105768,MANHATTAN,02/18/2013,04:25:00,NaN,NaN,13.0,02/18/2013,233,SEX CRIMES,"SEXUAL ABUSE 3,2",COMPLETED,MISDEMEANOR,FRONT OF,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,18-24,ASIAN / PACIFIC ISLANDER,F
105769,BROOKLYN,10/20/2016,19:30:00,10/20/2016,19:35:00,76.0,10/21/2016,233,SEX CRIMES,"SEXUAL ABUSE 3,2",COMPLETED,MISDEMEANOR,NaN,STREET,<18,BLACK,M,<18,BLACK,F
105770,MANHATTAN,03/13/2015,16:10:00,03/15/2015,16:11:00,17.0,03/16/2015,233,SEX CRIMES,"CHILD, ENDANGERING WELFARE",COMPLETED,MISDEMEANOR,INSIDE,COMMERCIAL BUILDING,25-44,WHITE HISPANIC,F,45-64,WHITE HISPANIC,F
105771,QUEENS,10/10/2014,13:05:00,NaN,NaN,110.0,10/21/2014,233,SEX CRIMES,"SEXUAL ABUSE 3,2",COMPLETED,MISDEMEANOR,INSIDE,PUBLIC SCHOOL,<18,WHITE HISPANIC,M,<18,WHITE HISPANIC,F
105772,QUEENS,06/25/2015,11:05:00,06/25/2015,11:06:00,115.0,06/25/2015,233,SEX CRIMES,"SEXUAL ABUSE 3,2",COMPLETED,MISDEMEANOR,FRONT OF,STREET,NaN,WHITE HISPANIC,M,45-64,WHITE HISPANIC,F

There is a typo in 2 rows, so I'm going to rename the elements.

In [7]:
nyc_SA_complaints.at[65823, 'start_date']= '10/11/2019'
nyc_SA_complaints.at[68821, 'start_date']= '10/11/2019'

#### Exporting nyc_SA_complaints DataFrame as a csv

In [8]:
nyc_SA_complaints.to_csv(r'../data/clean/NYPD_Complaint_Data_Historic_CLEAN_SA.csv')

### 3. Filtering the arrest data

1. Define a list of crime categories.
2. Read each line in the CSV file and look at the 9th field/column.
3. If it contains a string that is in the categories of interest, add current line to filter list.

In [9]:
arrest_filtered_lines = []
for lnum, line in enumerate(open('../data/raw/NYPD_Arrests_Data__Historic_.csv')):
    
    # add the first line of file into flitered_list (this is the column headers)
    if lnum==0:
        arrest_filtered_lines.append(line)
    
    # if the 9th field in the current line matches one of the string in SA_cats add to list
    fields = line.split(',')
    if fields[5] in SA_cats:
        arrest_filtered_lines.append(line)

In [10]:
with open('../data/raw/NYPD_Arrests_Data__Historic_FILTERED_SAcrimes.csv', 'w') as out:
    for line in arrest_filtered_lines:
        out.write(line)

### 4. Cleaning the arrests data
1. Look at the columns in data set
2. Filter for columns necessary for analysis 
3. Create a new data frame with just those columns
2. Rename columns

In [11]:
nyc_arrests_df = pd.read_csv('../data/raw/NYPD_Arrests_Data__Historic_FILTERED_SAcrimes.csv')

In [12]:
nyc_arrests_df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
0,144954157,07/31/2015,153,RAPE 3,104,RAPE,PL 1302502,F,Q,112,0,25-44,M,BLACK,1025420.0,202485.0,40.722364,-73.851474,POINT (-73.85147389399998 40.72236368700005)
1,143915509,06/23/2015,180,COURSE OF SEXUAL CONDUCT AGAINST A CHILD,116,SEX CRIMES,PL 130801B,F,M,25,0,18-24,M,WHITE HISPANIC,1000555.0,230994.0,40.800694,-73.941109,POINT (-73.94110928599997 40.800694331000045)
2,144128610,06/30/2015,157,RAPE 1,104,RAPE,PL 1303501,F,K,90,2,18-24,M,BLACK,997843.0,196573.0,40.706222,-73.950974,POINT (-73.95097435599996 40.70622201300005)
3,144454407,07/12/2015,168,SODOMY 1,116,SEX CRIMES,PL 1305001,F,K,81,0,45-64,M,BLACK,1005218.0,190528.0,40.689615,-73.924393,POINT (-73.92439311199998 40.689615497000034)
4,144342696,07/08/2015,157,RAPE 1,104,RAPE,PL 1303501,F,M,25,0,25-44,M,BLACK,1000555.0,230994.0,40.800694,-73.941109,POINT (-73.94110928599997 40.800694331000045)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22474,206870062,12/29/2019,157,RAPE 1,104,RAPE,PL 1303501,F,Q,112,0,18-24,M,BLACK,1025420.0,202485.0,40.722364,-73.851474,POINT (-73.85147389399998 40.72236368700005)
22475,204904841,11/08/2019,164,SODOMY 3,116,SEX CRIMES,PL 1304001,F,K,70,0,<18,M,AMERICAN INDIAN/ALASKAN NATIVE,991547.0,168934.0,40.630367,-73.973713,POINT (-73.97371261299998 40.63036654500007)
22476,206255195,12/10/2019,177,SEXUAL ABUSE,116,SEX CRIMES,PL 1306502,F,Q,112,0,45-64,M,WHITE HISPANIC,1025420.0,202485.0,40.722364,-73.851474,POINT (-73.85147389399998 40.72236368700005)
22477,205789935,11/29/2019,177,SEXUAL ABUSE,116,SEX CRIMES,PL 1306504,F,K,84,0,45-64,M,BLACK,989013.0,192652.0,40.695469,-73.982825,POINT (-73.98282507899995 40.69546894100006)
22478,203871125,10/17/2019,153,RAPE 3,104,RAPE,PL 1302501,F,B,47,0,18-24,F,WHITE HISPANIC,1026387.0,262634.0,40.887451,-73.847608,POINT (-73.84760778699996 40.88745131300004)

In [13]:
nyc_arrests_df.columns

Index(['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD',
       'Y_COORD_CD', 'Latitude', 'Longitude', 'Lon_Lat'],
      dtype='object')

In [14]:
cols2= ['ARREST_DATE','ARREST_BORO','ARREST_PRECINCT','KY_CD','OFNS_DESC','PD_DESC', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE']
nyc_SA_arrests = nyc_arrests_df[cols2]
cname_dict= {
    'ARREST_DATE': 'arrest_date',
    'ARREST_BORO': 'arrest_borough', 
    'ARREST_PRECINCT': 'arrest_precinct', 
    'KY_CD': 'classif_code',
    'OFNS_DESC': 'offense_desc',
    'PD_DESC': 'pd_desc',
    'AGE_GROUP': 'perp_age',
    'PERP_SEX': 'perp_sex',
    'PERP_RACE': 'perp_race', 
}
nyc_SA_arrests= nyc_SA_arrests.rename(columns=cname_dict)
nyc_SA_arrests

,arrest_date,arrest_borough,arrest_precinct,classif_code,offense_desc,pd_desc,perp_age,perp_sex,perp_race
0,07/31/2015,Q,112,104,RAPE,RAPE 3,25-44,M,BLACK
1,06/23/2015,M,25,116,SEX CRIMES,COURSE OF SEXUAL CONDUCT AGAINST A CHILD,18-24,M,WHITE HISPANIC
2,06/30/2015,K,90,104,RAPE,RAPE 1,18-24,M,BLACK
3,07/12/2015,K,81,116,SEX CRIMES,SODOMY 1,45-64,M,BLACK
4,07/08/2015,M,25,104,RAPE,RAPE 1,25-44,M,BLACK
...,...,...,...,...,...,...,...,...,...
22474,12/29/2019,Q,112,104,RAPE,RAPE 1,18-24,M,BLACK
22475,11/08/2019,K,70,116,SEX CRIMES,SODOMY 3,<18,M,AMERICAN INDIAN/ALASKAN NATIVE
22476,12/10/2019,Q,112,116,SEX CRIMES,SEXUAL ABUSE,45-64,M,WHITE HISPANIC
22477,11/29/2019,K,84,116,SEX CRIMES,SEXUAL ABUSE,45-64,M,BLACK
22478,10/17/2019,B,47,104,RAPE,RAPE 3,18-24,F,WHITE HISPANIC

#### Exporting nyc_SA_arrests DataFrame as a csv

In [15]:
nyc_SA_arrests.to_csv(r'../data/clean/NYPD_Arrests_Data_Historic_CLEAN_SA.csv')